# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'Firebase/Core'
pod 'react-native-camera', path: '../node_modules/react-native-camera'

target 'hunt' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hunt

  target 'huntTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
